### ISSUE TITLE
Enable h5ad files to be used as inputs to other workflows

### ISSUE THREAD

**Issue by cflerin** [vib-singlecell-nf/vsn-pipelines#110]
Currently h5ad input seems to be implemented only for `single_sample` by using the `h5ad_single_sample` entry point (from #49/#97).

If its possible, it would be much less confusing to be able to use `nextflow run [...] -entry single_sample` and have the input file type be automatically determined. Maybe we can have a separate function at the start of each workflow that handles the input data, then passes it on to to the workflow itself?

**Comment by dweemx** [comment]
Implemented in `v0.13.0`
