### ISSUE TITLE
Remove doublets (Scrublet)

### ISSUE THREAD

**Issue by jjans5** [vib-singlecell-nf/vsn-pipelines#113]
#not so nice

```
import scanpy as sc
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
adata = sc.read_h5ad("FCA_10x_All.SC__FILE_CONCATENATOR.h5ad")
adata_dr = sc.read_h5ad("FCA_10x_All.SC__SCANPY__DIM_REDUCTION_UMAP.h5ad")

#take variable genes from adata_dr
variable_genes = list(adata_dr.var.index[adata_dr.var['highly_variable']])
print(len(variable_genes))
doublet_cells_all = []

batches = list(set(adata.obs['batch']))
adata_objects_raw = {}
for batch in batches:
    adata_0 = adata[adata.obs['batch']==batch,:].copy()
    adata_dr_0 = adata_dr[adata_dr.obs['batch']==batch,:].copy()
    adata_0_var = adata_0.X[:,np.array(adata_dr_0.var['highly_variable'])] #use adata_dr_0 te keep genes at the same position, output is a matrix
    scrub = scr.Scrublet(adata_0_var)
    adata_0.obs['doublet_scores'], adata_0.obs['predicted_doublets'] = scrub.scrub_doublets(synthetic_doublet_umi_subsampling=0.5,n_prin_comps=50)
    scrub.plot_histogram()
    adata_objects_raw[batch] = adata_0
    #take doublet cells based on expected doublets based on number of cells (10x Chromium)
    #expected_doublets = np.int(len(adata_0)/100000*len(adata_0)) (updated see comments)
    cells_recovered = len(adata_0)
    doublet_rate = 0.0008 * cells_recovered + 0.0527
    expected_doublets = np.int(doublet_rate/100 * cells_recovered)


    doublet_cells = adata_0.obs['doublet_scores'].sort_values(ascending=False).head(n=expected_doublets).index
    doublet_cells_all = doublet_cells_all + list(doublet_cells)

adata_dr.obs['man_doublets'] = False
adata_dr.obs.loc[doublet_cells_all,'man_doublets'] = True
sc.pl.tsne(adata_dr, color='man_doublets',size=10,color_map='plasma_r')
```

**Comment by hejian41** [comment]
Hi Janssens,
I applied your script to remove doublets in my adata with three batch, but I found that the number of doublets predicted with your method was far more than that predicted separately (2594 vs. 67 of total 40700 cells). I was wondering if there was an overestimate regarding your method.

**Comment by jjans5** [comment]
Hi, 
I found that using scrublet only, with their thresholds was not working well. If you use 10x chromium, the technical data suggests that there is an increase of around 1% doublets for every 1000 cells per run (e.g. 5% doublets in a 5k cells run). Based on this number, I select the x% cells with the highest doublet score per run (batch) and call them doublets. This also means that having only 67 doublets in 40k cells (0.17%) is really low, and likely an underestimation.

Since it's a bit supervised I called it "not so nice", but it was the best I could find at the moment. If you have any suggestions feel free to let me know :) Also, when I checked it on a tSNE/UMAP, the doublets were nicely spread between clusters and showed expression of multiple markers, so in my dataset it did seem like they were real doublets. 

There are some more precise numbers on the increase of % of doublets with more cells/run, so I will update that soon :)

**Comment by jjans5** [comment]
%_doublets = 0.0008 * (cells_recovered) + 0.0527 based on 10x chromium v2 (https://assets.ctfassets.net/an68im79xiti/RT8DYoZzhDJRBMrJCmVxl/6a0ed8015d89bf9602128a4c9f8962c8/CG00052_SingleCell3_ReagentKitv2UserGuide_RevF.pdf ) 
and retained in 10x chromium v3 (https://assets.ctfassets.net/an68im79xiti/4tjk4KvXzTWgTs8f3tvUjq/2259891d68c53693e753e1b45e42de2d/CG000183_ChromiumSingleCell3__v3_UG_Rev_C.pdf)

**Comment by jjans5** [comment]
so this part: 
`expected_doublets = np.int(len(adata_0)/100000*len(adata_0))`

can be replaced by:
`cells_recovered = len(adata_0)`
`doublet_rate = 0.0008 * cells_recovered + 0.0527`
`expected_doublets = np.int(doublet_rate/100 * cells_recovered) `

**Comment by hejian41** [comment]
I fully agree with you that  there is an underestimation using scrublet only (right). Also, the doublets estimated with your script in my dataset seem to be real doublets (left).  Your method is quite robust. Thanks！
![doublets](https://user-images.githubusercontent.com/38309419/77407910-e41eef80-6df1-11ea-8ddf-b588372f1437.png)
