### ISSUE TITLE
Report processes are not resuming

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#135]

**Comment by cflerin** [comment]
Could this be due to setting `overwrite: true` in the `publishDir` command?

https://github.com/vib-singlecell-nf/scanpy/blob/8ab5d125442dd0d52934e4d265b06ab2e3129a63/processes/reports.nf#L18

**Comment by dweemx** [comment]
Could be, to be tested; why did we set this to true ?

**Comment by cflerin** [comment]
I did this when changing the reports to hard links, but I can't remember why overwrite was necessary...

**Comment by dweemx** [comment]
I think you are right:
https://www.nextflow.io/docs/latest/process.html#publishdir
```
When true any existing file in the specified folder will be overridden (default: true during normal pipeline execution and false when pipeline execution is resumed).
```

**Comment by dweemx** [comment]
I actually don't think it's coming from the `overwrite` attribute since other processes do have this too
