### ISSUE TITLE
Generate example data repo

### ISSUE THREAD

**Issue by KrisDavie** [vib-singlecell-nf/vsn-pipelines#151]
We should generate a repository where we can deposit configurations and test data alongside outputs of the pipeline, so that people can test and ensure they obtain the correct output.

This should stay out of the main repo so that we keep the size down.

We should also look into removing these files from the history of this repo to shrink the repo size (currently 51Mb, of which ~35Mb is this type of data)

**Comment by KrisDavie** [comment]
Repository is created here: https://github.com/vib-singlecell-nf/examples

Data/reports should be moved and history rewritten to remove large files from this repo.

**Comment by dweemx** [comment]
Shall we then remove the folder `examples` in `vsn-pipelines` ?

**Comment by cflerin** [comment]
The new example repo is here:
https://github.com/vib-singlecell-nf/vsn-pipelines-examples

with docs here:
https://vsn-pipelines-examples.readthedocs.io/en/latest/index.html
