### ISSUE TITLE
Failed: bbknn generate report and loom

### ISSUE THREAD

**Issue by IrinaMate** [vib-singlecell-nf/vsn-pipelines#170]
`[9d/de566e] process > bbknn:BBKNN:BEC_BBKNN:SC__SCANPY__DIM_REDUCTION__UMAP (1)                                   [100%] 1 of 1 ✔
[a9/07df14] process > bbknn:BBKNN:BEC_BBKNN:SC__PUBLISH_H5AD (1)                                                  [100%] 1 of 1 ✔
[46/9c1af5] process > bbknn:BBKNN:BEC_BBKNN:GENERATE_DUAL_INPUT_REPORT:SC__SCANPY__GENERATE_DUAL_INPUT_REPORT (1) [100%] 1 of 1, failed: 1 ✘
[-        ] process > bbknn:BBKNN:BEC_BBKNN:GENERATE_DUAL_INPUT_REPORT:SC__SCANPY__REPORT_TO_HTML                 -
[d4/c5d3d3] process > bbknn:BBKNN:SC__H5AD_TO_FILTERED_LOOM                                                       [100%] 1 of 1 ✔
[1a/f0245b] process > bbknn:BBKNN:FILE_CONVERTER:SC__H5AD_TO_LOOM (1)                                             [100%] 1 of 1, failed: 1
[-        ] process > bbknn:BBKNN:FILE_CONVERTER:COMPRESS_HDF5                                                    -
[08/a485dc] process > bbknn:BBKNN:UTILS__GENERATE_WORKFLOW_CONFIG_REPORT                                          [100%] 1 of 1 ✔
[-        ] process > bbknn:BBKNN:SC__SCANPY__MERGE_REPORTS                                                       -
[-        ] process > bbknn:BBKNN:SC__SCANPY__REPORT_TO_HTML`

`Work dir:
/ddn1/vol1/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_v3_vs_NextGem/2samples_control/MCF7_subset/bbknn/new/work/46/9c1af5886524355168b1a245d30b04`

**Comment by dweemx** [comment]
Is there any error (i.e.: red text) raised by nextflow ?

**Comment by IrinaMate** [comment]
`Error executing process > 'bbknn:BBKNN:BEC_BBKNN:GENERATE_DUAL_INPUT_REPORT:SC__SCANPY__GENERATE_DUAL_INPUT_REPORT (1)'

Caused by:
  Process `bbknn:BBKNN:BEC_BBKNN:GENERATE_DUAL_INPUT_REPORT:SC__SCANPY__GENERATE_DUAL_INPUT_REPORT (1)` terminated with an error exit status (1)

Command executed:

  papermill sc_bbknn_report.ipynb                   --report-mode                       10x_v3_vs_NextGem_subset_MCF7control.bknn.SC_BEC_BBKNN_report.ipynb
        -p FILE1 10x_v3_vs_NextGem_subset_MCF7control.bknn.SC__SCANPY__MARKER_GENES.h5ad -p FILE2 10x_v3_vs_NextGem_subset_MCF7control.bknn.BEC_BBKNN.output.h5ad
        -y "annotations_to_plot: []
  "                     -p WORKFLOW_MANIFEST '{"nextflowVersion":"!19.12.0-edge","defaultBranch":"master","version":"0.14.2","homePage":"https://github.com/vib-singlecell-nf/vsn-pipelines","gitmodules":null,"description":"A repository of pipelines for single-cell data in Nextflow DSL2","name":"vib-singlecell-nf/vsn-pipelines","mainScript":"main.nf","author":null}'
        -p WORKFLOW_PARAMETERS '{"global":{"project_name":"10x_v3_vs_NextGem_subset_MCF7control.bknn","outdir":"out","qsubaccount":"","qsubemail":"","seed":142},"sc":{"scope":{"genome":"","tree":{"level_1":"","level_2":"","level_3":""}},"file_converter":{"tagCellWithSampleId":true,"useFilteredMatrix":true,"iff":"h5ad"},"file_concatenator":{"join":"outer","off":"h5ad"},"scanpy":{"container":"vibsinglecellnf/scanpy:0.5.0","report":{"annotations_to_plot":[]},"feature_selection":{"report_ipynb":"/src/scanpy/bin/reports/sc_select_variable_genes_report.ipynb","method":"mean_disp_plot","minMean":0.0125,"maxMean":3,"minDisp":0.5,"off":"h5ad"},"feature_scaling":{"method":"zscore_scale","maxSD":10,"off":"h5ad"},"neighborhood_graph":{"nPcs":50,"off":"h5ad"},"dim_reduction":{"report_ipynb":"/src/scanpy/bin/reports/sc_dim_reduction_report.ipynb","pca":{"method":"pca","nComps":50,"off":"h5ad"},"umap":{"method":"umap","off":"h5ad"},"tsne":{"method":"tsne","nJobs":10,"off":"h5ad"}},"clustering":{"report_ipynb":"/src/scanpy/bin/reports/sc_clustering_report.ipynb","method":"louvain","resolution":0.4,"off":"h5ad"},"marker_genes":{"method":"wilcoxon","ngenes":0,"groupby":"louvain","off":"h5ad"},"filter":{"report_ipynb":"/src/scanpy/bin/reports/sc_filter_qc_report.ipynb","cellFilterMinNGenes":{"TEW__0ca12c__MCF_control_V3":2200,"TEW__af8998__MCF7_control_NextGEM":2500},"cellFilterMaxNGenes":{"TEW__0ca12c__MCF_control_V3":7000,"TEW__af8998__MCF7_control_NextGEM":7500},"cellFilterMaxPercentMito":0.2,"geneFilterMinNCells":3,"off":"h5ad","outdir":"out"},"data_transformation":{"method":"log1p","off":"h5ad"},"normalization":{"method":"cpx","countsPerCellAfter":10000,"off":"h5ad"},"batch_effect_correct":{"method":"bbknn","report_ipynb":"/src/scanpy/bin/reports/sc_bbknn_report.ipynb","neighborsWithinBatch":5,"nPcs":20,"trim":0,"off":"h5ad"}}},"utils":{"container":"vibsinglecellnf/utils:0.2.1","workflow_configuration":{"report_ipynb":"/src/utils/bin/reports/workflow_configuration_template.ipynb"}},"data":{"h5ad":{"file_paths":"/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_v3_vs_NextGem/single_samples/TEW__0ca12c__MCF_control_V3/MCF7_subset/TEW__0ca12c__MCF_control_V3.h5ad,/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_v3_vs_NextGem/single_samples/TEW__af8998__MCF7_control_NextGEM/MCF7subset/TEW__af8998__MCF7_control_NextGEM.h5ad","suffix":".h5ad"}}}'

Command exit status:
  1

Command output:
  (empty)

Command error:
      297     If `show==False` a :class:`~matplotlib.axes.Axes` or a list of it.
      298     """
  --> 299     return plot_scatter(adata, 'umap', **kwargs)
      300
      301

  /opt/venv/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in plot_scatter(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, arrows, arrows_kwds, groups, components, layer, projection, color_map, palette, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
      154             adata, value_to_plot, layer=layer,
      155             groups=groups, palette=palette,
  --> 156             use_raw=use_raw, gene_symbols=gene_symbols,
      157         )
      158

  /opt/venv/lib/python3.7/site-packages/scanpy/plotting/_tools/scatterplots.py in _get_color_values(adata, value_to_plot, groups, palette, use_raw, gene_symbols, layer)
      694         value_to_plot = adata.var.index[adata.var[gene_symbols] == value_to_plot][0] # TODO: Throw helpful error if this doesn't work
      695     if use_raw and value_to_plot not in adata.obs.columns:
  --> 696         values = adata.raw.obs_vector(value_to_plot)
      697     else:
      698         values = adata.obs_vector(value_to_plot, layer=layer)

  /opt/venv/lib/python3.7/site-packages/anndata/core/anndata.py in obs_vector(self, k)
      411         as `.obs_names`.
      412         """
  --> 413         idx = self._normalize_indices((slice(None), k))
      414         a = self.X[idx]
      415         if issparse(a):

  /opt/venv/lib/python3.7/site-packages/anndata/core/anndata.py in _normalize_indices(self, packed_index)
      362         obs, var = unpack_index(packed_index)
      363         obs = _normalize_index(obs, self._adata.obs_names)
  --> 364         var = _normalize_index(var, self.var_names)
      365         return obs, var
      366

  /opt/venv/lib/python3.7/site-packages/anndata/core/anndata.py in _normalize_index(index, names)
      153         return slice(start, stop, step)
      154     elif isinstance(index, (np.integer, int, str)):
  --> 155         return name_idx(index)
      156     elif isinstance(index, (Sequence, np.ndarray, pd.Index)):
      157         # here, we replaced the implementation based on name_idx with this

  /opt/venv/lib/python3.7/site-packages/anndata/core/anndata.py in name_idx(i)
      140                 raise IndexError(
      141                     'Key "{}" is not valid observation/variable name/index.'
  --> 142                     .format(i))
      143             i = i_found[0]
      144         return i

  IndexError: Key "sample_id" is not valid observation/variable name/index.

Work dir:
  /ddn1/vol1/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_v3_vs_NextGem/2samples_control/MCF7_subset/bbknn/new/work/46/9c1af5886524355168b1a245d30b04

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out``

**Comment by dweemx** [comment]
Do you run it from `github` or did you clone the repo ?
Could you share the command you use to run the pipeline ?

**Comment by IrinaMate** [comment]
`nextflow -C MCF7_subset_control.bbknn.config run vib-singlecell-nf/vsn-pipelines -entry bbknn`

path: `/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_v3_vs_NextGem/2samples_control/MCF7_subset/bbknn/new`

The input samples are in h5ad format. I've runned them with harmony and that was fine

**Comment by dweemx** [comment]
Could you run `nextflow pull vib-singlecell-nf/vsn-pipelines` and try again for `bbknnn` ?

**Comment by IrinaMate** [comment]
same outcome. I'll try with other samples and see if fails as well

**Comment by dweemx** [comment]
I've narrowed down the bug; I'll let you know when it's fixed

**Comment by dweemx** [comment]
Currently fixed in `develop` branch; wait for next release
