### ISSUE TITLE
sample_id is neither included in the AnnData obs nor displayed in batch effect correction reports anymore

### ISSUE THREAD

**Issue by IrinaMate** [vib-singlecell-nf/vsn-pipelines#171]
sample_id was quite useful especially when integrating multiple samples

**Comment by dweemx** [comment]
You experienced this bug when running the pipelines with `.h5ad` as input data format ?

**Comment by IrinaMate** [comment]
Indeed that's the case

**Comment by dweemx** [comment]
This should be fixed in the `develop` branch:
```
nextflow \
   -C test_h5ad_input.bbknn.config \
   run \
      -r develop vib-singlecell-nf/vsn-pipelines \
      -entry bbknn \
      -resume
```

**Comment by IrinaMate** [comment]
ok I was actually running harmony  🤓 but I'll move to develop branch

**Comment by dweemx** [comment]
Whatever the batch effect correction method you are using, it should be fixed if you use `-r develop`.
Let me know it this works for you ;)

**Comment by IrinaMate** [comment]
yes sample_id is back

**Comment by IrinaMate** [comment]
now I noticed that is back in clustering report but not in Single-Cell Report: Harmony Batch Correction report

**Comment by dweemx** [comment]
What do you mean by `sample_id` "is back" in ... but not in ... ?

**Comment by IrinaMate** [comment]
![image](https://user-images.githubusercontent.com/53533047/76785471-ce884500-67b5-11ea-9939-645f0037cf91.png)
![image (1)](https://user-images.githubusercontent.com/53533047/76785508-dea02480-67b5-11ea-9ff8-c7dcd325d96a.png)

**Comment by dweemx** [comment]
This should be fixed in `develop` branch
