### ISSUE TITLE
[BUG] File converted crashes on non-unique gene index

### ISSUE THREAD

**Issue by KrisDavie** [vib-singlecell-nf/vsn-pipelines#188]
**Describe the bug**
Any sample put through the file converter with duplicate genes will cause the pipeline to crash because of this line: https://github.com/vib-singlecell-nf/vsn-pipelines/blob/master/src/utils/bin/sc_file_converter.py#L139

The sort fails because of the duplicate elements.
Adding `adata.var_names_make_unique()` before this line (https://anndata.readthedocs.io/en/stable/anndata.AnnData.var_names_make_unique.html) adds a suffix to the gene names and allows the sort.

**To Reproduce**
1. Configure with these options:
```
nextflow config vib-singlecell-nf/vsn-pipelines -profile singularity,tenx,single_sample > nextflow.config
```

2. Run using this entry point:
```
nextflow -C nextflow.config run vib-singlecell-nf/vsn-pipelines -entry single_sample
```
Must be done on a sample with duplicate gene names

3. See error:

Lost the error in scroll history, but it was during the converter step and the error was that it could not be reindexed with duplicate values

**Expected behavior**
Continuation with no error

**Please complete the following information:**
 - OS: Ubuntu 18.04
 - Nextflow Version: 19.12.0-edge
 - vsn-pipelines Version: e.g. 0.15.1

**Comment by dweemx** [comment]
This is fixed in 7c400eafebf0d4b3142d975829402afa695fa6d8
