### ISSUE TITLE
[BUG] A fresh user cannot pull the repo via nextflow with no github ssh login set up 

### ISSUE THREAD

**Issue by KrisDavie** [vib-singlecell-nf/vsn-pipelines#203]
**Describe the bug**
A fresh user cannot pull the repo via nextflow with no github ssh login set up 

**To Reproduce**
1. Be a new user with no ssh keys or config
2. `nextflow pull vib-singlecell-nf/vsn-pipelines`

3. See error:

```
$ nextflow pull vib-singlecell-nf/vsn-pipelines
Checking vib-singlecell-nf/vsn-pipelines ...
git@github.com:vib-singlecell-nf/cellranger.git: UnknownHostKey: github.com. RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48
```

**Expected behavior**
Pipeline should pull successfully 

**Please complete the following information:**
 - OS: CentOS7
 - Nextflow Version: 19.12.0-edge
 - vsn-pipelines Version: 0.17.0

**Comment by mzager** [comment]
I believe this issue was reintroduced with the addition of SoupX - FYI

**Comment by dweemx** [comment]
Yes indeed;
Thanks @KrisDavie

**Comment by dweemx** [comment]
Pulling from master should now work.
Also updated release `v0.20.0` to target the latest commit on master
