### ISSUE TITLE
[BUG] SCRUBLET__DOUBLET_REMOVAL:PUBLISH_SCRUBLET_OBJECT

### ISSUE THREAD

**Issue by IrinaMate** [vib-singlecell-nf/vsn-pipelines#215]
**Describe the bug**
Scrublet error when running multi samples with the single_sample_scrublet
Scanpy part run without problems. For scrublet failed at first sample  SCRUBLET__DOUBLET_REMOVAL:PUBLISH_SCRUBLET_OBJECT

**To Reproduce**
1. Configure with these options:

```nextflow config vib-singlecell-nf/vsn-pipelines -profile scrublet,tenx,singularity,single_sample > Single_samples_scublet.config```

2. Run using this entry point:

``` nextflow -C Single_samples_scublet.config run -r develop vib-singlecell-nf/vsn-pipelines -entry single_sample_scrublet```

3. See error:

```Error executing process > 'single_sample_scrublet:SCRUBLET__DOUBLET_REMOVAL:PUBLISH_SCRUBLET_OBJECT:SC__PUBLISH (1)'

Caused by:
  Process `single_sample_scrublet:SCRUBLET__DOUBLET_REMOVAL:PUBLISH_SCRUBLET_OBJECT:SC__PUBLISH (1)` terminated with an error exit status (1)

Command executed:

  cp -rL TEW__3109c1__MCF7_cells_ctrl_rep2.SC__SCRUBLET__DOUBLET_DETECTION.ScrubletObject.pklz tmp
  ln tmp "TEW__3109c1__MCF7_cells_ctrl_rep2.SC__SCRUBLET__DOUBLET_DETECTION.ScrubletObject.pklz"
  rm tmp

Command exit status:
  1

Command output:
  (empty)

Command error:
  ln: failed to create hard link ‘TEW__3109c1__MCF7_cells_ctrl_rep2.SC__SCRUBLET__DOUBLET_DETECTION.ScrubletObject.pklz’: File exists

Work dir:
  /ddn1/vol1/staging/leuven/stg_00002/lcb/lcb_projects/TEW/MCF7/10x/ControlvsTSA/analysis_irina/10x_MCF7_cells_vs_nuclei/single_samples/single_samples/work/83/12f7c558809c3d2dc440a97778ee52

...
```

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Ubuntu
 - Nextflow Version: 20.04.1
 - vsn-pipelines Version: 0.19.0

**Additional context**

**Comment by dweemx** [comment]
Hi @IrinaMate,
I added a potential fix in the `develop` branch, could check if this solves your issue ?

**Comment by IrinaMate** [comment]
is fixed ..Thanks
