### ISSUE TITLE
[SUGGESTION] Improve interoperability with Scanpy

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#233]
**Is your feature request related to a problem? Please describe.**
It would be nice that the any pipeline would generate a:
- [x] SCope-ready loom
- [x] Scanpy-ready h5ad

**Describe the solution you'd like**
Along the the final ouput of the pipelines (currently SCope-ready), 2 additional files should be generated that are Scanpy-ready.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by ghuls** [comment]
@dweemx Maybe this could be helpful: https://github.com/mojaveazure/seurat-disk

**Comment by dweemx** [comment]
Yeah I know about this one but I haven't tried yet.
Definitely need some custom code because we multiple have multiple embeddings and clusterings that are stored in a particular way in the `SCope-ready` loom.
