### ISSUE TITLE
[BUG]Module compile error

### ISSUE THREAD

**Issue by xuzhougeng** [vib-singlecell-nf/vsn-pipelines#250]
**Describe the bug**

When I run the quick test as descripted in https://vsn-pipelines.readthedocs.io/en/latest/getting-started.html 

I met the following problem.

![image](https://user-images.githubusercontent.com/19432485/98803131-42671400-244f-11eb-9795-cec12423a6d8.png)

To fix this problem, I used the same version 19.10.0 in quick start, and I get the following error message.

![image](https://user-images.githubusercontent.com/19432485/98803580-f5d00880-244f-11eb-9be1-6b7a36391abc.png)

Then I still use the newest version of nextflow, but  replace the variable `channel` to `ch` in tenx.nf and file.nf.

And I can get the following message.

![image](https://user-images.githubusercontent.com/19432485/98803463-bd302f00-244f-11eb-9808-4245ce9df541.png)

Finally I know I need to use the  nextflow (v 20.04 ) to run this pipeline.

Could you add the this version requirement message in the README and tutorial ? Or add the version check code in main.nf at beginning?

**Comment by dweemx** [comment]
Hi @xuzhougeng ,

Thanks for reporting back. 
It seems that Nextflow version `20.10.0` has introduced some backward incompatible changes.
I have updated the docs as suggested. These changes are currently in the `develop` branch: https://vsn-pipelines.readthedocs.io/en/develop/getting-started.html

**Comment by semir2** [comment]
Thanks，I got same error and  sovled with your help.
