### ISSUE TITLE
[SUGGESTION] Upgrade to Nextflow Version 20.10.0

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#253]
**Is your feature request related to a problem? Please describe.**
Upgrade to Nextflow Version 20.10.0.

**Describe the solution you'd like**
Update code so that all pipelines work with latest Nextflow version.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by cflerin** [comment]
It's worth noting that the new Nextflow version is causing the problems seen in #250

**Comment by dweemx** [comment]
This will be planned after the upgrade to a single unified repository
