### ISSUE TITLE
[SUGGESTION] Merge submodules into a single unified repository

### ISSUE THREAD

**Issue by cflerin** [vib-singlecell-nf/vsn-pipelines#259]
**Is your feature request related to a problem? Please describe.**
The use of submodules is valuable for modularity and keeping an organized project structure with some modules potentially working on their own without the parent `vsn-pipelines`. However, the drawbacks are:
- Overhead in development of creating and maintaining separate repositories for each tool
- Difficult to review pull requests that include code that is modified in submodules (and sometimes in multiple submodules in one PR).
- Difficult to manage commit links to the submodules
- Difficult to easily make large-scale changes that affect all submodules (requires updating each submodule separately, and relinking to the main repo).

**Describe the solution you'd like**
Merge all of the submodules into a single unified repository, keeping the current directory structure in `src/`.

---
### Submodules to be merged:
These can be marked when all branches have been merged into the submodule master branch.

- [x] [archr](https://github.com/vib-singlecell-nf/archr)
- [x] [bap](https://github.com/vib-singlecell-nf/bap)
- [x] [bwamaptools](https://github.com/vib-singlecell-nf/bwamaptools)
- [x] [celda](https://github.com/vib-singlecell-nf/celda)
- [x] [cellranger](https://github.com/vib-singlecell-nf/cellranger)
- [x] [cellranger-atac](https://github.com/vib-singlecell-nf/cellranger-atac)
- [x] [directs](https://github.com/vib-singlecell-nf/directs)
- [x] [dropletutils](https://github.com/vib-singlecell-nf/dropletutils)
- [x] [dropseqtools](https://github.com/vib-singlecell-nf/dropseqtools)
- [x] [edirect](https://github.com/vib-singlecell-nf/edirect)
- [x] [fastp](https://github.com/vib-singlecell-nf/fastp)
- [x] [flybaser](https://github.com/vib-singlecell-nf/flybaser)
- [x] [harmony](https://github.com/vib-singlecell-nf/harmony)
- [x] [pcacv](https://github.com/vib-singlecell-nf/pcacv)
- [x] [picard](https://github.com/vib-singlecell-nf/picard)
- [x] [popscle](https://github.com/vib-singlecell-nf/popscle)
- [x] [pycistopic](https://github.com/vib-singlecell-nf/pycistopic)
- [x] [scanpy](https://github.com/vib-singlecell-nf/scanpy)
- [x] [scenic](https://github.com/vib-singlecell-nf/scenic)
- [x] [scrublet](https://github.com/vib-singlecell-nf/scrublet)
- [ ] [Seurat](https://github.com/Qlostridium/Seurat) (currently an external repo)
- [ ] [SingleCellExperiment](https://github.com/Qlostridium/SingleCellExperiment) (currently an external repo)
- [ ] [DoubletFinder](https://github.com/Qlostridium/DoubletFinder) (currently an external repo)
- [x] [singlecelltoolkit](https://github.com/vib-singlecell-nf/singlecelltoolkit)
- [x] [sinto](https://github.com/vib-singlecell-nf/sinto)
- [ ] [slingshot](https://github.com/vib-singlecell-nf/slingshot)
- [x] [soupx](https://github.com/vib-singlecell-nf/soupx)
- [x] [sratoolkit](https://github.com/vib-singlecell-nf/sratoolkit)
- [x] [star](https://github.com/vib-singlecell-nf/star)
- [x] [trimgalore](https://github.com/vib-singlecell-nf/trimgalore)

#### Modules to be kept separate:
- [template](https://github.com/vib-singlecell-nf/template)
- [vsn-pipelines-examples](https://github.com/vib-singlecell-nf/vsn-pipelines-examples)

#### Old/unused modules:
- [cistopic](https://github.com/vib-singlecell-nf/cistopic)
- [snaptools](https://github.com/vib-singlecell-nf/snaptools)

**Comment by KrisDavie** [comment]
All used submodules are now merged with histories, with the exception of cellranger-atac, which lost its history.
Large file blobs have been removed.
