### ISSUE TITLE
[BUG] Failed to publish file across filesystems

### ISSUE THREAD

**Issue by cflerin** [vib-singlecell-nf/vsn-pipelines#265]
**Describe the bug**
All publish steps fail to complete when the Nextflow work directory and the current working directory are on different filesystems.

**To Reproduce**
1. Configure with these options:

Use the `NXF_WORK` environmental variable to direct all working files to a scratch drive that's on a different filesystem than the current working directory. Test with any of the test profiles:
```
nextflow pull vib-singlecell-nf/vsn-pipelines -r v0.23.0

export NXF_WORK=/ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp
```

2. Run using this entry point:
```
nextflow run vib-singlecell-nf/vsn-pipelines -profile scenic,test__scenic,singularity -entry scenic -r v0.23.0
```

3. See error:
These are warnings and the pipeline reports that it completes successfully, but there is no output data in the `out` directory:
```
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/77/c96d18799ed09bb8629fa2b43066fc/expr_mat_tiny.loom; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/scenic/scenic_CI/cistarget/expr_mat_tiny.loom [link] -- See log file for details
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/77/c96d18799ed09bb8629fa2b43066fc/scenic_CI__reg_mtf.csv.gz; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/scenic/scenic_CI/cistarget/scenic_CI__reg_mtf.csv.gz [link] -- See log file for details
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/e4/e0b523315c1aa3a54f20007a054098/expr_mat_tiny.loom; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/scenic/scenic_CI/aucell/expr_mat_tiny.loom [link] -- See log file for details
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/e4/e0b523315c1aa3a54f20007a054098/scenic_CI__auc_mtf.loom; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/scenic/scenic_CI/aucell/scenic_CI__auc_mtf.loom [link] -- See log file for details
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/da/146559f2ea88adaccba7d20b0aa383/scenic_visualize.loom; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/scenic/scenic_CI/SCENIC_SCope_output.loom [link] -- See log file for details
WARN: Failed to publish file: /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/62/52a6bc5eddae9cd9ba5916966dc4ae/scenic_CI.SCENIC.loom; to: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/data/scenic_CI.SCENIC.loom [link] -- See log file for details
```
And an excerpt from the log reports `Invalid cross-device link`:
```
java.nio.file.FileSystemException: /ddn1/vol1/staging/leuven/stg_00002/lcb/cflerin/analysis/pbmc_atac/analysis/nextflow/cross_filesystem_publish/out/data/scenic_CI.SCENIC.loom -> /ddn1/vol1/site_scratch/leuven/325/vsc32528/vsn_tmp/62/52a6bc5eddae9cd9ba5916966dc4ae/scenic_CI.SCENIC.loom: Invalid cross-device link
```

**Expected behavior**
Cross-filesystem publishing should work.

**Screenshots**
NA

**Please complete the following information:**
- OS: CentOS Linux release 7.8.2003 (Core)
- Nextflow Version: 20.04.1
- vsn-pipelines Version: v0.23.0

**Additional context**
NA

**Comment by KrisDavie** [comment]
I think this needs to just be documented for users to understand that links don't work across file systems. Our other option is to convert to copying for publishing rather than sym/hard linking, that will always work, but of course will take more space when people don't clear their work folders.

**Comment by cflerin** [comment]
There must a better solution than to just say that this won't work at all. As a user, if I see that this `NXF_WORK` environmental variable is available in Nextflow, then it's reasonable to expect that it would work here.

Possible solutions:
1. Switching everything to copy would indeed be a quick fix for all of this, and working directories should be treated as temporary use in any case.
1. We can provide a parameter in the config that controls whether publish is done via hardlink or copy.

With option 2, the publish directives become:
```
process SC__PUBLISH {

    publishDir "${params.global.outdir}/data/intermediate", \
        mode: "${params.utils.publish.mode}", \
        saveAs: {
            filename -> "${outputFileName}"
        }

...
```
I've tested this briefly and it works for `symlink`, `link`, and `copy` methods in `params.utils.publish.mode`. I would also remove `overwrite: true` in this case to avoid re-copying large files, which can take a significant amount of time for many large files.

**Comment by dweemx** [comment]
I like option 2 better (as you described) and setting probably `symlink` as default 
Also good idea to remove `overwrite: true`

**Comment by cflerin** [comment]
I implemented option 2 above, but using `link` as the default (this is how it was in the existing code anyway).

**Comment by Zifeng1995** [comment]
> It seems there are a few places where the publish mode is hardcoded in the [loomHandler.nf](https://github.com/vib-singlecell-nf/vsn-pipelines/blob/master/src/scenic/processes/loomHandler.nf) processes.
> 
> But to get these files immediately you can just copy them using the full source and destination paths from the warning, for example:
> 
> ```
> cp \
>   /cluster/home/zfli/test/single_sample_test/work/5e/e00c91db073fe4576372b28d935b48/1k_pbmc_v3_chemistry.SC__H5AD_TO_LOOM.loom \
>   /cluster/home/zfli/test/single_sample_test/out/loom/1k_pbmc_v3_chemistry.SCope_output.loom
> ```

Thanks for your help! I got it!
