### ISSUE TITLE
[SCANPY] Mitochondrial plots in QC report not working for non-human genomes or those with gene identifiers (e.g.: EnsemblID)

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#269]
This is because we are specifically looking for genes starting with 'MT-':
https://github.com/aertslab/SingleCellTxBenchmark/blob/a75de242a0cabe525897a96b139e3eadc9248372/src/scanpy/bin/filter/sc_cell_filter.py#L106

**Comment by cflerin** [comment]
Closing in favor of #264
