### ISSUE TITLE
[BUG] Pulling new version v0.24.0 fails if old version exists

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#282]
**Describe the bug**
If a version of VSN ` <= v0.23.0` is already existing, pulling the new version v0.24.0 will faill.

**To Reproduce**
1. Configure with these options:
None

2. Run using this entry point:

```
nextflow pull vib-singlecell-nf/vsn-pipelines
```

3. See error:

```
Checking vib-singlecell-nf/vsn-pipelines ...
Project config file is malformed -- Cause: Compile failed for sources FixedSetSources[name='/groovy/script/Script3F83C31ACD3B56601BB35A21D6E3EC5A/_nf_config_488d7e18']. Cause: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/groovy/script/Script3F83C31ACD3B56601BB35A21D6E3EC5A/_nf_config_488d7e18: 6: unexpected token: << @ line 6, column 1.
   <<<<<<< HEAD
   ^
1 error
```

**Expected behavior**
New version of the repository should be pulled without error.

**Screenshots**

**Please complete the following information:**
 - OS: `CentOS`
 - Nextflow Version: `20.04.1`
 - vsn-pipelines Version: `<= v0.23.0`

**Additional context**

**Comment by dweemx** [comment]
The solution to this is to remove the old cached version of VSN-Pipelines (`<= v0.23.0`) and pulling the new version.
```
# Remove the old cached version
rm -r ~/.nextflow/assets/vib-singlecell-nf/vsn-pipelines

# Pull a fresh copy of the repository
nextflow pull vib-singlecell-nf/vsn-pipelines
```

**Comment by cflerin** [comment]
Adding the `f` flag will make this a bit easier by skipping the checks on all of the git files:

```rm -rf ~/.nextflow/assets/vib-singlecell-nf/vsn-pipelines```
