### ISSUE TITLE
[SUGGESTION] Avoid correction of barcode names

### ISSUE THREAD

**Issue by cbravo93** [vib-singlecell-nf/vsn-pipelines#288]
**Is your feature request related to a problem? Please describe.**
In 10X data, barcode names generally have '-[0-9]' at the end (e.g. ATGCTGCTCTA-1). I noticed that the number is removed in the pipeline, resulting in barcode-sample_id (e.g. ATGCTGCTCTA-Sample_1). However, for downstream analyses, and eventually working with fragments files for the multiome having the initial number is very relevant. 

**Describe the solution you'd like**
Would it be possible to return the cell names as barcode-number-sample_id? E.g ATGCTGCTCTA-1-Sample_1

**Comment by cbravo93** [comment]
I also found a solution to remove the '-1' from the fragments file; however the fastest I managed was 1 min/file (for average runs with ~5K cells).

**Comment by cflerin** [comment]
Seems that this is coded here:
https://github.com/vib-singlecell-nf/vsn-pipelines/blob/91e572484a335ff2766dbbb60a7dcb90ab1c7590/src/utils/bin/sc_file_converter.py#L130

and three entries in the R version:
https://github.com/vib-singlecell-nf/vsn-pipelines/blob/91e572484a335ff2766dbbb60a7dcb90ab1c7590/src/utils/bin/sc_file_converter.R#L123-L127

**Comment by dweemx** [comment]
Yes, I added so that it's easier to identify the cells w/o having to mask them first.
But indeed, we could leave this index in place I guess ?

**Comment by cbravo93** [comment]
That would be great (or at least giving it as an option)! I found solutions to work with the fragments file without it, but it slows things significantly: while it is true that normally we work with single GEMs ('-1'), I can't assume it will always be like this. Keeping the index would make it very straight forward :)

**Comment by dweemx** [comment]
@cbravo93 yes indeed would be better and more robust for later. Let's append the sample name to the complete cell barcode.

**Comment by dweemx** [comment]
@cbravo93 this is fixed in `develop` branch. By default now it will append the sample to the complete cell barcode. We still keep the old way by setting a new param `remove10xGEMWell` in the `publish` scope of the config.
