### ISSUE TITLE
Scrublet metadata in loom is nan [BUG]

### ISSUE THREAD

**Issue by cbravo93** [vib-singlecell-nf/vsn-pipelines#302]
**Describe the bug**
When running a scrublet workflow, the metadata in the loom for predicted_doublets and doublet_scores is nan.

**Screenshots**
![image](https://user-images.githubusercontent.com/19205518/107346755-5ad5e180-6ac5-11eb-92e8-4899d7e704ef.png)

**Please complete the following information:**
 - OS: [Ubuntu]
 - Nextflow Version: [20.04.1]
 - vsn-pipelines Version: [latest]

**Additional context**
The scrublet metadata tsv looks correct, so this can be fixed a posteriori.

**Comment by cbravo93** [comment]
This one is very likely related to running decontx before. Scrublet doublet scores are all 0.

**Comment by cbravo93** [comment]
I reopen the issue since some people has reported a similar problem in slack. In this case the pipeline did finished.

**Comment by IrinaMate** [comment]
experienced similar issues. decontx is interfering with scrublet output

**Comment by dweemx** [comment]
@IrinaMate should be fixed in `develop`
