### ISSUE TITLE
[SUGGESTION] Update scanpy

### ISSUE THREAD

**Issue by cflerin** [vib-singlecell-nf/vsn-pipelines#316]
**Is your feature request related to a problem? Please describe.**
General updates to the Scanpy tool (solutions to e.g. #300)

**Describe the solution you'd like**
Update scanpy and anndata to the latest version: `1.8.1` ?

**Describe alternatives you've considered**

**Additional context**

**Comment by dweemx** [comment]
Would be also nice here to fix #285 #299

**Comment by cflerin** [comment]
> Would be also nice here to fix #285 #299

Yes, these will be taken care of here when we update the associated packages

**Comment by KrisDavie** [comment]
Closed #358
