### ISSUE TITLE
failed to create hard link ‘pbmc10k_data.SCANPY.hvg_scaled_output.h5ad’ => ‘tmp’: Operation not permitted

### ISSUE THREAD

**Issue by vagabond12** [vib-singlecell-nf/vsn-pipelines#317]
centos7.7
nextflow version  20.10.0.5430
vsn-pipelines Version  0.25.0

nextflow -C pbmc10k.vsn-pipelines.complete.config \
    run vib-singlecell-nf/vsn-pipelines \
    -entry single_sample \
     -r v0.25.0

**Describe the bug**

[pbmc10k_data, /home/jxx2/Tutorials/SCENIC_pbmc/pbmc10k_data/outs, 10x_cellranger_mex_outs, h5ad]
Error executing process > 'single_sample:SINGLE_SAMPLE:SCANPY__SINGLE_SAMPLE:HVG_SELECTION:PUBLISH_H5AD_HVG_SCALED:SC__PUBLISH (1)'

Caused by:
  Process `single_sample:SINGLE_SAMPLE:SCANPY__SINGLE_SAMPLE:HVG_SELECTION:PUBLISH_H5AD_HVG_SCALED:SC__PUBLISH (1)` terminated with an error exit status (1)

Command executed:

  mv pbmc10k_data.SCANPY.hvg_scaled_output.h5ad tmp
  if [ ! -f pbmc10k_data.SCANPY.hvg_scaled_output.h5ad ]; then
      ln -L tmp "pbmc10k_data.SCANPY.hvg_scaled_output.h5ad"
  fi

Command exit status:
  1

Command output:
  (empty)

Command error:
  ln: failed to create hard link ‘pbmc10k_data.SCANPY.hvg_scaled_output.h5ad’ => ‘tmp’: Operation not permitted

Work dir:
  /home/jxx2/Tutorials/SCENIC_pbmc/work/7d/7c3d7ff02cdf4adc14c4b8d1062342

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
WARN: Killing pending tasks (4)

**Comment by cflerin** [comment]
Hi @vagabond12 ,

This should be fixed in the `develop` branch. You can update your local copy using:
```
nextflow pull vib-singlecell-nf/vsn-pipelines -r develop
```

**Comment by Ijoanito** [comment]
Hi @cflerin, 
I also experience similar problem but on different file:

![image](https://user-images.githubusercontent.com/52953881/110808071-a1824b80-82be-11eb-8125-8f53d180dd6b.png)

I then try your suggestion to use the develop version, but I get another error:

"Unknown error accessing project `vib-singlecell-nf/vsn-pipelines` -- Repository may be corrupted: /home/ubuntu/.nextflow/assets/vib-singlecell-nf/vsn-pipelines"

This is how I run it (my nextflow version is 20.10.0):
nextflow -C single_sample.config run vib-singlecell-nf/vsn-pipelines -r -entry single_sample

**Comment by cflerin** [comment]
Hi @Ijoanito ,

It seems like your local copy was corrupted somehow. Best thing to do would be to remove it and re-pull it. See the [comment here](https://github.com/vib-singlecell-nf/vsn-pipelines/issues/282#issuecomment-745206537) for how to do this.

Keep in mind that if you are switching from a release to the develop branch, you may have to re-generate your config file (`nextflow config ...`) as we have changed some parameters since the last relase.

**Comment by Ijoanito** [comment]
Hi @cflerin 

Thanks for your prompt reply. 

Yes I have tried that one too. This is how I run it:

rm -rf ~/.nextflow/assets/vib-singlecell-nf/vsn-pipelines
nextflow pull vib-singlecell-nf/vsn-pipelines -r develop
nextflow config vib-singlecell-nf/vsn-pipelines -profile tenx,docker,single_sample > single_sample.config
nextflow -C single_sample.config run vib-singlecell-nf/vsn-pipelines -r -entry single_sample

This the config file that I use.
[single_sample.config.txt](https://github.com/vib-singlecell-nf/vsn-pipelines/files/6124131/single_sample.config.txt)

**Comment by cflerin** [comment]
Hi @Ijoanito ,

And you still get an error after running these commands, or not? It looks like there is a typo in your run command -- you haven't specified branch `develop`. It should be:
```
nextflow -C single_sample.config run vib-singlecell-nf/vsn-pipelines -r develop -entry single_sample
```

**Comment by Ijoanito** [comment]
Gezz, I didnt notice that. It is running perfectly now. 
Thanks a lot @cflerin!

**Comment by cflerin** [comment]
@Ijoanito , glad to hear that it's working for you now!
