### ISSUE TITLE
[SUGGESTION] Add zlib-ng for speedup of gzip/zlib (de)compression

### ISSUE THREAD

**Issue by dweemx** [vib-singlecell-nf/vsn-pipelines#325]
**Is your feature request related to a problem? Please describe.**

Improve parts of pipelines where compression/decompression is occurring.
From @ghuls: zlib-ng should speeding up some parts of the pipeline (gzip/zlib decompression speed x2, gzip/zlib compression speed x4).

**Describe the solution you'd like**

Use `zlib-ng` instead of `zlib` library
From @ghuls:
- For tools using there own `zlib` implentation, use `minigzip` instead of zip.
- For tools that use and link to `zlib`, adding the `zlib-ng` library path to `LD_LIBRARY_PATH` should be enough

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by cflerin** [comment]
I added two Dockerfiles under `/src/samtools/`:
- A base image that has zlib-ng and libdeflate. Can be used as a base for:
  - [ ] `trimgalore`
  - [ ] `samtools`
- A samtools (1.12) image built on this base. Can be used as a base for:
  - [ ] `popscle`
  - [ ] `bwamaptools`
  - [ ] `singlecelltoolkit`
