### ISSUE TITLE
[BUG] the Nextflow version reported in the docs is likely wrong

### ISSUE THREAD

**Issue by lucacozzuto** [vib-singlecell-nf/vsn-pipelines#329]
**Describe the bug**
I got an error launching the pipeline with the test dataset with version 20.04.1 

**To Reproduce**
I just followed the guide at https://vsn-pipelines.readthedocs.io/en/latest/getting-started.html#quick-start 
When defining Nextflow version 20.04.1 as indicated it crashes saying

```
No such variable: enable
```
When using version 20.10.0 seems to work.

**Comment by dweemx** [comment]
Hey @lucacozzuto, thanks for reporting the bug, we will include a fix in the next version (`v0.26.0`).
