### ISSUE TITLE
[BUG] output without suffix, and no loom published

### ISSUE THREAD

**Issue by atomnh** [vib-singlecell-nf/vsn-pipelines#345]
**Describe the bug**
When I run the PBMC example of scenic_multirun (v0.26.0) as the **Docs** indicated, The publication process has some issues, files under out/data/ without suffix, like this:

**sample_data.10x_PBMC.single_sample.final_output.** -> scenic_multirun/test/64/17c197846f07aa2ecd44492afd6e73/sample_data.SC__SCANPY__MARKER_GENES.h5ad
**sample_data.SINGLE_SAMPLE.** -> scenic_multirun/test/a5/68de6af1c4ee49eebbf96ba219237c/sample_data.SINGLE_SAMPLE.loom

And the file loom file cannot export successful with warning:
Jul-03 16:53:32.742 [Task monitor] WARN  nextflow.processor.PublishDir - Failed to publish file:
single_sample_test/work/8e/b8586d6505dc4cb69d680d0d0644e6/1k_pbmc_v3_chemistry.SC__H5AD_TO_LOOM.loom; to: single_sample_test/out/loom/1k_pbmc_v3_chemistry.SCope_output.loom [link] -- See log file for details

**To Reproduce**
1. Configure with these options:
```
I follow the tutorials in the Docs (https://vsn-pipelines-examples.readthedocs.io/en/latest/PBMC10k_multiruns.html) to adjust the configure file
```

2. Run using this entry point:

```
nextflow -C pbmc10k.vsn-pipelines.complete.config run vib-singlecell-nf/vsn-pipelines -entry single_sample

```

3. See error:

```
filenames of files under out/data are lack of suffixes, and no loom file was exported to out/loom

```

**Expected behavior**
I want the filename under out/data to be completed as it supposed to be: 
     sample_data.10x_PBMC.single_sample.final_output.h5ad -> scenic_multirun/test/64/17c197846f07aa2ecd44492afd6e73/sample_data.SC__SCANPY__MARKER_GENES.h5ad
   sample_data.SINGLE_SAMPLE.loom -> scenic_multirun/test/a5/68de6af1c4ee49eebbf96ba219237c/sample_data.SINGLE_SAMPLE.loom

**Please complete the following information:**
 - OS: CentOS v7
 - Nextflow Version: 20.10.0.5
 - vsn-pipelines Version: 0.26

**Comment by cflerin** [comment]
Thanks for the report @atomnh. This should be fixed in the latest release.
