### ISSUE TITLE
Set a fixed seed for all steps

### ISSUE THREAD

**Issue by cflerin** [vib-singlecell-nf/vsn-pipelines#43]
Especially important for dimensionality reduction, clustering, etc.

**Comment by dweemx** [comment]
Current stochastic processes:
- `SC__SCANPY__NEIGHBORHOOD_GRAPH` (`scanpy` repo)
- `SC__SCANPY__DIM_REDUCTION` (`scanpy` repo): concerns only UMAP
- `PCACV__FIND_OPTIMAL_NPCS` (`pcacv` repo)

**Comment by cflerin** [comment]
Nice work on this @dweemx ! But it's not quite finished for the pySCENIC steps. Maybe it would be better if we start another issue in that repo? It would need work on the pySCENIC codebase before we're able to implement anything here.

**Comment by dweemx** [comment]
What did I miss ?
I think I set the seed for the GRN step ;
Is there also some randomness in the cistarget/AUCell steps ?
Yeah, fine to create another issue in the `scenic` repo :+1:

**Comment by cflerin** [comment]
No you didn't miss anything. But there some things internal to pySCENIC (ctx and aucell steps) that are still stochastic. I'll start an issue there.

**Comment by dweemx** [comment]
This regards the following processes:
- SC__SCANPY__DIM_REDUCTION

`random_state` parameters are not passed to
- `sc.tl.tsne`
- `sc.tl.umap`

**Comment by dweemx** [comment]
Fully reproducible workflows from version `v0.13.0`

**Comment by erwinlagu** [comment]
Good Job
